[package]
name = "randomduck/astro-starter-meow"
version = "0.2.4"
description = "Astro.dev Wasmer starter package"
readme = "README.md"
repository = "https://github.com/ayys/astro-starter-meow"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
